# Generated by Django 3.2.13 on 2022-04-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='post',
            name='txId',
        ),
    ]
